import json
import re

# Comprehensive phrase and sentence translations for Hindi (hi) and Marathi (mr)
# covering every headline, paragraph, card, metric, badge, tab, form field, placeholder, button,
# graph node, telemetry status, SDG title, timeline note, team member, contact details, FAQ, and footer.

translations_hi = {
    # Paragraphs & Long Descriptions
    "To establish a nationwide digital grid where zero citizen distress calls go unanswered, and every engineering student graduates with verified, real-world societal problem-solving experience backed by government NOC clearance and institutional recognition.": "एक देशव्यापी डिजिटल ग्रिड स्थापित करना जहां नागरिकों की कोई भी समस्या अनसुनी न रहे, और प्रत्येक इंजीनियरिंग छात्र सरकारी एनओसी मंजूरी और संस्थागत मान्यता के साथ सत्यापित सामाजिक समस्याओं को हल करने का अनुभव प्राप्त करे।",
    "To seamlessly unify the Ministry of Education, AICTE academic frameworks, Municipal Corporations, District Collectors, and Corporate CSR wings under a single cryptographic, AI-driven workflow that matches ground challenges to college labs in real time.": "शिक्षा मंत्रालय, एआईसीटीई अकादमिक ढांचे, नगर निगमों, जिला कलेक्टरों और कॉरपोरेट सीएसआर विंग्स को एक एआई-संचालित वर्कफ़्लो के तहत निर्बाध रूप से जोड़ना जो वास्तविक समय में कॉलेज लैब से जमीनी चुनौतियों का मिलान करता है।",
    "Severe industrial arsenic runoff affecting Bhiwandi rural blocks. Recommended project architecture: solar-powered UV/Arsenic electro-flocculation unit paired with real-time sub-surface telemetry nodes reporting to district dashboard.": "भिवंडी ग्रामीण क्षेत्रों को प्रभावित करने वाला गंभीर औद्योगिक आर्सेनिक रिसाव। अनुशंसित परियोजना वास्तुकला: सौर-संचालित यूवी/आर्सेनिक इलेक्ट्रो-फ्लोकुलेशन इकाई जो जिला डैशबोर्ड को रिपोर्ट करने वाले रियल-टाइम टेलीमेट्री नोड्स के साथ जुड़ी है।",
    "C2C is integrated directly with AICTE Activity Point guidelines. When a student team completes a ground solution endorsed by their faculty guide and municipal inspector, credits are pushed directly into their university transcript.": "C2C को सीधे एआईसीटीई गतिविधि बिंदु दिशानिर्देशों के साथ एकीकृत किया गया है। जब कोई छात्र टीम अपने संकाय गाइड और नगर पालिका निरीक्षक द्वारा समर्थित समाधान पूरा करती है, तो क्रेडिट सीधे उनके विश्वविद्यालय टेप में स्थानांतरित कर दिए जाते हैं।",
    "Citizens, municipal counselors, or local ward heads submit ground issues via text, photos, or voice notes. The C2C AI semantic engine geotags the issue, removes duplicate entries, and verifies municipal urgency within 24 hours.": "नागरिक, नगर पार्षद, या स्थानीय वार्ड प्रमुख टेक्स्ट, फोटो या वॉयस नोट्स के माध्यम से जमीनी मुद्दे प्रस्तुत करते हैं। C2C AI इंजन इस मुद्दे को जियोटैग करता है, डुप्लिकेट प्रविष्टियों को हटाता है, और 24 घंटे के भीतर नगरपालिका की तात्कालिकता सत्यापित करता है।",
    "Yes. All CSR contributions are managed via escrow contracts compliance-mapped to Companies Act Section 135. Automated milestone reports, municipal utilization certificates, and receipt tokens are generated upon every payout.": "हां। सभी सीएसआर योगदान कंपनियों के अधिनियम की धारा 135 के अनुपालन-मैप किए गए एस्क्रो अनुबंधों के माध्यम से प्रबंधित किए जाते हैं। प्रत्येक भुगतान पर स्वचालित मील का पत्थर रिपोर्ट, नगर पालिका उपयोग प्रमाण पत्र और रसीद टोकन उत्पन्न होते हैं।",
    "Institutional heads can register directly on the C2C portal using their official domain email (.edu.in or .gov.in). Account clearance takes less than 2 hours following automated credential verification.": "संस्थागत प्रमुख अपने आधिकारिक डोमेन ईमेल (.edu.in या .gov.in) का उपयोग करके सीधे C2C पोर्टल पर पंजीकरण कर सकते हैं। स्वचालित क्रेडेंशियल सत्यापन के बाद खाता मंजूरी में 2 घंटे से भी कम समय लगता है।",
    "Direct access to AI-matched community challenges that align with university curriculum credits. Form interdisciplinary teams, unlock hardware stipends, and submit verified engineering solutions.": "विश्वविद्यालय के पाठ्यक्रम क्रेडिट के साथ संरेखित एआई-मिलान वाली सामुदायिक चुनौतियों तक सीधी पहुंच। अंतर-विषय टीमों का गठन करें, हार्डवेयर वजीफा अनलॉक करें और सत्यापित इंजीनियरिंग समाधान प्रस्तुत करें।",
    "Sovereign digital bridge unifying Smart India Hackathon innovators, public administration, university research, and civic ground telemetry for verified societal impact.": "स्मार्ट इंडिया हैकाथॉन नवप्रवर्तकों, सार्वजनिक प्रशासन, विश्वविद्यालय अनुसंधान और नागरिक जमीनी टेलीमेट्री को एकजुट करने वाला डिजिटल सेतु।",
    "Transforms vernacular or voice distress reports into structured engineering specs, automatically routing them to department labs based on faculty domain expertise.": "स्थानीय भाषा या वॉयस रिपोर्टों को संरचित इंजीनियरिंग स्पेक्स में परिवर्तित करता है, जो संकाय की विशेषज्ञता के आधार पर स्वचालित रूप से विभाग प्रयोगशालाओं को रूट करता है।",
    "Empowering ward counselors, village sarpanches, and citizens to register distress vectors with automated GPS tagging and NLP deduplication.": "वार्ड पार्षदों, ग्राम सरपंचों और नागरिकों को स्वचालित जीपीएस टैगिंग और एनएलपी डुप्लीकेशन के साथ संकट के मुद्दों को पंजीकृत करने के लिए सशक्त बनाना।",
    "Direct CSR funding, tech hardware grants, and executive engineering mentorship under formalized Section 135 compliance.": "औपचारिक धारा 135 अनुपालन के तहत प्रत्यक्ष सीएसआर वित्तपोषण, तकनीक हार्डवेयर अनुदान और कार्यकारी इंजीनियरिंग सलाह।",
    "Real-time telemetry measuring social return on investment, state-by-state resolution velocities, and UN SDG alignment.": "निवेश पर सामाजिक रिटर्न, राज्य-वार समाधान वेग और संयुक्त राष्ट्र एसडीजी संरेखण को मापने वाली रियल-टाइम टेलीमेट्री।",
    "From ground-level citizen distress calls to verified societal deployment, every milestone is auditable and automated.": "जमीनी स्तर के नागरिक संकट कॉल से लेकर सत्यापित सामाजिक तैनाती तक, हर मील का पत्थर ऑडिट योग्य और स्वचालित है।",
    "Engineered for high-volume civic scale, regulatory Section 135 compliance, and frictionless cross-sector execution.": "उच्च-स्तरीय नागरिक पैमाने, नियामक धारा 135 अनुपालन और घर्षण रहित क्रॉस-सेक्टर निष्पादन के लिए इंजीनियर।",
    "Discover and report ground-level issues with spatial GIS mapping, population density indexing, and urgency scoring.": "स्थानिक जीआईएस मैपिंग, जनसंख्या घनत्व इंडेक्सिंग और तात्कालिकता स्कोरिंग के साथ जमीनी स्तर के मुद्दों की खोज करें और रिपोर्ट करें।",
    "Geo-tagged submissions via web portal, vernacular voice notes, or WhatsApp bots by panchayats and local residents.": "पंचायत और स्थानीय निवासियों द्वारा वेब पोर्टल, स्थानीय वॉयस नोट्स या व्हाट्सएप बॉट्स के माध्यम से जियो-टैग की गई प्रविष्टियां।",
    "Automated ESG reporting and Social Return on Investment (SROI) metrics formatted directly for ministerial review.": "मंत्रालयी समीक्षा के लिए सीधे तैयार की गई स्वचालित ईएसजी रिपोर्टिंग और निवेश पर सामाजिक रिटर्न (एसआरओआई) मेट्रिक्स।",
    "Neural vector scoring linking citizen distress vectors to collegiate engineering proficiencies and lab inventory.": "नागरिक संकट वैक्टरों को कॉलेज इंजीनियरिंग दक्षताओं और प्रयोगशाला सूची से जोड़ने वाली तंत्रिका वेक्टर स्कोरिंग।",
    "Pitch multidisciplinary solutions, earn verified AICTE academic credit points, and register provisional patents.": "बहु-विषयक समाधान पेश करें, सत्यापित एआईसीटीई अकादमिक क्रेडिट अंक अर्जित करें और अनंतिम पेटेंट पंजीकृत करें।",
    "Milestone-governed execution with verifiable digital proofs of work, GitHub linkage, and geofenced field audits.": "काम के सत्यापन योग्य डिजिटल प्रमाण, गिटहब लिंकेज और जियोफेंस्ड क्षेत्र ऑडिट के साथ मील का पत्थर-शासित निष्पादन।",
    "NLP models perform cross-regional deduplication, priority grading, and cross-reference with municipal datasets.": "एनएलपी मॉडल क्रॉस-रीजनल डुप्लीकेशन, प्राथमिकता ग्रेडिंग और नगर पालिका डेटासेट के साथ क्रॉस-संदर्भ करते हैं।",
    "Connect department research labs with municipal challenges. Turn final-year capstone theses into field pilots.": "विभाग अनुसंधान प्रयोगशालाओं को नगर पालिका चुनौतियों से जोड़ें। अंतिम वर्ष के कैपस्टोन थेसिस को फील्ड पायलटों में बदलें।",
    "Direct portal for District Collectors and Municipal Commissioners to validate pilot proposals within 48 hours.": "जिला कलेक्टरों और नगर आयुक्तों के लिए 48 घंटों के भीतर पायलट प्रस्तावों को मान्य करने का सीधा पोर्टल।",
    "Algorithms pair the verified challenge with student engineering cohorts, department labs, and faculty guides.": "एल्गोरिदम सत्यापित चुनौती का छात्र इंजीनियरिंग समूहों, विभाग प्रयोगशालाओं और संकाय गाइडों के साथ मिलान करते हैं।",
    "Interdisciplinary squads assemble (e.g., 3 engineers + 1 data scientist) under an accredited faculty mentor.": "एक मान्यता प्राप्त संकाय संरक्षक के तहत अंतर-विषय दल (जैसे, 3 इंजीनियर + 1 डेटा वैज्ञानिक) एकत्र होते हैं।",
    "Immutable impact quantified: liters purified, kWh saved, citizen hours recovered, and Social ROI calculated.": "अपरिवर्तनीय प्रभाव परिमाणित: शुद्ध लीटर, बचाई गई kWh, नागरिक घंटे बरामद, और सामाजिक ROI की गणना।",
    "Prototypes live in community. Real-time IoT feedback and citizen satisfaction ratings stream to dashboards.": "प्रोटोटाइप समुदाय में लाइव हैं। रियल-टाइम आईओटी फीडबैक और नागरिक संतुष्टि रेटिंग डैशबोर्ड पर आती हैं।",
    "University lab facilities and professors certify hardware safety, sensor calibration, and code stability.": "विश्वविद्यालय प्रयोगशाला सुविधाएं और प्रोफेसर हार्डवेयर सुरक्षा, सेंसर अंशांकन और कोड स्थिरता को प्रमाणित करते हैं।",
    "Upon dispatch, 4 shortlisted universities within a 50km radius and 2 CSR partners receive automated RFPs.": "प्रेषण पर, 50 किमी के दायरे में 4 शॉर्टलिस्ट किए गए विश्वविद्यालय और 2 सीएसआर भागीदारों को स्वचालित आरएफपी प्राप्त होते हैं।",
    "Autonomous edge-AI drone scans for pink bollworm detection across smallholder cotton belts in Vidarbha.": "विदर्भ में छोटे कपास क्षेत्रों में गुलाबी बॉलवर्म का पता लगाने के लिए स्वायत्त एज-एआई ड्रोन स्कैन।",
    "\"Hi! I'm C2C AI. Let's turn a civic challenge into an actionable solution. How can I guide you today?\"": "\"नमस्ते! मैं C2C AI हूँ। आइए एक नागरिक चुनौती को कार्रवाई योग्य समाधान में बदलें। मैं आज आपका मार्गदर्शन कैसे कर सकता हूँ?\"",
    "Corporate CSR capital, cloud compute credits, and hardware toolkits route directly to project escrow.": "कॉरपोरेट सीएसआर पूंजी, क्लाउड कंप्यूट क्रेडिट और हार्डवेयर टूलकिट सीधे प्रोजेक्ट एस्क्रो को रूट करते हैं।",
    "Continuous cellular temperature telemetry for primary healthcare storage in Gadchiroli tribal belts.": "गडचिरोली आदिवासी क्षेत्रों में प्राथमिक स्वास्थ्य देखभाल भंडारण के लिए निरंतर सेलुलर तापमान टेलीमेट्री।",
    "District Collectors authorize testing grounds and road-cutting NOCs with zero bureaucratic delay.": "जिला कलेक्टर शून्य नौकरशाही देरी के साथ परीक्षण मैदान और सड़क काटने की एनओसी को अधिकृत करते हैं।",
    "Partner: Bhiwandi Municipal Council • Host: Veermata Jijabai Technological Institute (VJTI)": "भागीदार: भिवंडी नगर परिषद • मेजबान: वीरमाता जीजाबाई टेक्नोलॉजिकल इंस्टीट्यूट (VJTI)",
    
    # Titles & Headlines
    "Sovereign Civic Orchestrator": "संप्रभु नागरिक आर्केस्ट्रेटर",
    "Bridging Campus Innovation & Community Distress": "कैंपस इनोवेशन और सामुदायिक संकट को जोड़ना",
    "Real-World Problem to Verified Solution Pipeline": "वास्तविक समस्या से सत्यापित समाधान पाइपलाइन",
    "Live Sovereign Infrastructure Telemetry": "लाइव संप्रभु बुनियादी ढांचा टेलीमेट्री",
    "Grassroots Challenge Intake Pipeline": "तृणमूल चुनौती इनटेक पाइपलाइन",
    "National Social ROI & SDG Dashboard": "राष्ट्रीय सामाजिक ROI और SDG डैशबोर्ड",
    "Architected for Every Sovereign Stakeholder": "हर संप्रभु हितधारक के लिए डिज़ाइन किया गया",
    "4-Phase Sovereign Governance Lifecycle": "4-चरण संप्रभु शासन जीवनचक्र",
    "Frequently Asked Questions": "अक्सर पूछे जाने वाले प्रश्न",
    "Ready to Transform Your Campus Innovation?": "क्या आप अपने कैंपस इनोवेशन को बदलने के लिए तैयार हैं?",
    "About Campus2Community": "Campus2Community के बारे में",
    "Core Vision & Mission": "मुख्य विजन और मिशन",
    "Our Vision": "हमारा विजन",
    "Our Mission": "हमारा मिशन",
    "Core Platform Pillars": "मुख्य प्लेटफॉर्म स्तंभ",
    "Evolution & Milestones": "विकास और उपलब्धियां",
    "Unified Platform Core Team": "एकीकृत प्लेटफॉर्म कोर टीम",

    # Section Subtitles & Badges
    "GOVERNMENT APPROVED CIVIC INFRASTRUCTURE": "सरकार द्वारा स्वीकृत नागरिक बुनियादी ढांचा",
    "SIH 2026 FIELD INTAKE PIPELINE": "SIH 2026 फील्ड इनटेक पाइपलाइन",
    "LIVE TELEMETRY & DISPATCH MATRIX": "लाइव टेलीमेट्री और प्रेषण मैट्रिक्स",
    "QUANTIFIABLE SOCIETAL ROI": "मात्रात्मक सामाजिक ROI",
    "UNIFIED STAKEHOLDER VALUE": "एकीकृत हितधारक मूल्य",
    "GROUND-TO-GOVERNMENT LIFECYCLE": "जमीन से सरकार जीवनचक्र",
    "EVERYTHING YOU NEED TO KNOW": "सब कुछ जो आपको जानना आवश्यक है",
    "JOIN THE SOVEREIGN MESH": "संप्रभु मेश में शामिल हों",
    "CAMPUS2COMMUNITY ECOSYSTEM": "कैंपस2कम्युनिटी पारिस्थितिकी तंत्र",
    "VIDYALANKAR INSTITUTE OF TECHNOLOGY (VSIT)": "विद्यालंकार इंस्टीट्यूट ऑफ टेक्नोलॉजी (VSIT)",

    # Card & Node Titles
    "Students & Innovators": "छात्र और नवप्रवर्तक",
    "Universities & Labs": "विश्वविद्यालय और प्रयोगशालाएं",
    "Faculty Mentorship": "संकाय मार्गदर्शन",
    "Field NGO Coalition": "क्षेत्र गैर सरकारी संगठन गठबंधन",
    "Social Auditing": "सामाजिक लेखा परीक्षा",
    "Industry CSR Escrow": "उद्योग सीएसआर एस्क्रो",
    "Sec 135 Compliance": "धारा 135 अनुपालन",
    "Government NOC": "सरकारी एनओसी",
    "District Administration": "जिला प्रशासन",
    "Urban Local Bodies": "शहरी स्थानीय निकाय",

    # Metric & Stats Labels
    "Active Solvers": "सक्रिय समाधानकर्ता",
    "Campuses": "कैंपस",
    "Verifiers": "सत्यापनकर्ता",
    "Committed": "प्रतिबद्ध",
    "CITIZENS BENEFITED": "लाभान्वित नागरिक",
    "COMMUNITIES IMPACTED": "प्रभावित समुदाय",
    "PROBLEMS SOLVED": "हल की गई समस्याएं",
    "ACTIVE CAPSTONE PROJECTS": "सक्रिय कैपस्टोन परियोजनाएं",
    "WATER & SANITATION (SDG 6)": "जल और स्वच्छता (SDG 6)",
    "AGRITECH & SOIL HEALTH (SDG 2)": "एग्रीटेक और मृदा स्वास्थ्य (SDG 2)",
    "SMART INFRASTRUCTURE (SDG 11)": "स्मार्ट इंफ्रास्ट्रक्चर (SDG 11)",
    "RURAL HEALTHCARE (SDG 3)": "ग्रामीण स्वास्थ्य देखभाल (SDG 3)",

    # Filter Options & Form Fields
    "All Categories": "सभी श्रेणियां",
    "Water Systems": "जल प्रणालियां",
    "Urban Roads": "शहरी सड़कें",
    "Solar Microgrids": "सौर माइक्रोग्रिड",
    "Rural Health": "ग्रामीण स्वास्थ्य",
    "Civic Infrastructure": "नागरिक बुनियादी ढांचा",
    "Agriculture Tech": "कृषि तकनीक",
    "Filter by Keyword or District...": "कीवर्ड या जिले द्वारा फ़िल्टर करें...",
    "Search Problems...": "समस्याएँ खोजें...",
    "Search tickets, districts, SDGs...": "टिकट, जिले, एसडीजी खोजें...",
    "Select Priority": "प्राथमिकता चुनें",
    "Critical (ULB 24h SLA)": "गंभीर (ULB 24h SLA)",
    "High Urgency": "उच्च तात्कालिकता",
    "Medium Urgency": "मध्यम तात्कालिकता",
    "Low Urgency": "कम तात्कालिकता",

    # Buttons & Actions
    "Explore Problem Mesh": "समस्या मेश का अन्वेषण करें",
    "Submit Field Distress Report": "फील्ड संकट रिपोर्ट जमा करें",
    "Submit Ticket to Sovereign Mesh": "संप्रभु मेश में टिकट जमा करें",
    "Trigger Auto-NOC Dispatch": "ऑटो-एनओसी प्रेषण ट्रिगर करें",
    "View Gazetted Consent Certificate": "राजपत्रित सहमति प्रमाणपत्र देखें",
    "Join 32,000+ Student Engineers": "32,000+ छात्र इंजीनियरों से जुड़ें",
    "Explore SIH 2026 Portal": "SIH 2026 पोर्टल का अन्वेषण करें",
    "Register Institution / Student Team": "संस्थान / छात्र टीम पंजीकृत करें",

    # Navigation & Footers
    "Overview": "अवलोकन",
    "Intake Pipeline": "इनटेक पाइपलाइन",
    "AI Orchestrator": "एआई आर्केस्ट्रेटर",
    "Impact Telemetry": "प्रभाव टेलीमेट्री",
    "Stakeholders": "हितधारक",
    "Governance & SIH": "प्रशासन और SIH",
    "About Us & Platform Vision": "हमारे बारे में और मंच विज़न",
    "Code Base & Tech Specs": "कोड बेस और तकनीकी विनिर्देश",
    "Ministry of Education": "शिक्षा मंत्रालय",
    "AICTE Portal Integration": "एआईसीटीई पोर्टल एकत्रीकरण",
    "SIH 2026 Grand Finale": "SIH 2026 ग्रँड फिनाले",

    # Single Words & Common Terms
    "Students": "छात्र",
    "Innovators": "नवप्रवर्तक",
    "Universities": "विश्वविद्यालय",
    "Labs": "प्रयोगशालाएं",
    "Faculty": "संकाय",
    "Mentorship": "मार्गदर्शन",
    "Field": "क्षेत्र",
    "NGO": "एनजीओ",
    "Coalition": "गठबंधन",
    "Verifiers": "सत्यापनकर्ता",
    "Social": "सामाजिक",
    "Auditing": "लेखा परीक्षा",
    "Industry": "उद्योग",
    "Escrow": "एस्क्रो",
    "Committed": "प्रतिबद्ध",
    "Compliance": "अनुपालन",
    "Government": "सरकार",
    "District": "जिला",
    "Administration": "प्रशासन",
    "Urban": "शहरी",
    "Local": "स्थानीय",
    "Bodies": "निकाय",
    "Active": "सक्रिय",
    "Solvers": "समाधानकर्ता",
    "Campuses": "कैंपस",
    "Ticket": "टिकट",
    "Problem": "समस्या",
    "Solution": "समाधान",
    "Status": "स्थिति",
    "Verified": "सत्यापित",
    "Pending": "लंबित",
    "Resolved": "हल किया गया",
    "Details": "विवरण",
    "Filter": "फ़िल्टर",
    "Search": "खोजें",
    "Submit": "जमा करें",
    "Close": "बंद करें",
    "Back": "वापस",
    "Next": "अगला",
    "Previous": "पिछला",
    "All": "सभी",
    "Critical": "गंभीर",
    "High": "उच्च",
    "Medium": "मध्यम",
    "Low": "कम"
}

translations_mr = {
    # Paragraphs & Long Descriptions
    "To establish a nationwide digital grid where zero citizen distress calls go unanswered, and every engineering student graduates with verified, real-world societal problem-solving experience backed by government NOC clearance and institutional recognition.": "नागरिकांची कोणतीही तक्रार अनुत्तरित राहणार नाही अशी देशव्यापी डिजिटल ग्रिड स्थापन करणे, आणि प्रत्येक अभियांत्रिकी विद्यार्थ्याला शासकीय NOC मंजुरी व संस्थात्मक मान्यतेसह प्रत्यक्ष सामाजिक समस्या सोडवण्याचा अनुभव मिळवून देणे.",
    "To seamlessly unify the Ministry of Education, AICTE academic frameworks, Municipal Corporations, District Collectors, and Corporate CSR wings under a single cryptographic, AI-driven workflow that matches ground challenges to college labs in real time.": "शिक्षण मंत्रालय, AICTE शैक्षणिक फ्रेमवर्क, महानगरपालिका, जिल्हा जिल्हाधिकारी आणि कॉर्पोरेट CSR विभागांना एकाच AI-चलित वर्कफ्लोमध्ये एकत्रित करणे जे प्रत्यक्ष समस्यांचे कॉलेज लॅब्सशी रीअल-टाइम जुळवणी करते.",
    "Severe industrial arsenic runoff affecting Bhiwandi rural blocks. Recommended project architecture: solar-powered UV/Arsenic electro-flocculation unit paired with real-time sub-surface telemetry nodes reporting to district dashboard.": "भिवंडी ग्रामीण भागाला प्रभावित करणारा गंभीर औद्योगिक आर्सेनिक प्रवाह. शिफारस केलेले प्रकल्प स्वरूप: सौरउर्जेवर चालणारे UV/आर्सेनिक इलेक्ट्रो-फ्लॉक्युलशन युनिट जे जिल्हा डॅशबोर्डला रिपोर्ट करणाऱ्या रिअल-टाइम टेलिमेट्री नोड्सशी जोडलेले आहे.",
    "C2C is integrated directly with AICTE Activity Point guidelines. When a student team completes a ground solution endorsed by their faculty guide and municipal inspector, credits are pushed directly into their university transcript.": "C2C हे थेट AICTE अ‍ॅक्टिव्हिटी पॉइंट मार्गदर्शक तत्त्वांशी एकत्रित केले आहे. जेव्हा एखादी विद्यार्थी टीम त्यांच्या प्राध्यापक मार्गदर्शक आणि पालिका निरीक्षकाने मंजूर केलेले समाधान पूर्ण करते, तेव्हा क्रेडिट्स थेट त्यांच्या विद्यापीठ ट्रान्सक्रिप्टमध्ये जोडले जातात.",
    "Citizens, municipal counselors, or local ward heads submit ground issues via text, photos, or voice notes. The C2C AI semantic engine geotags the issue, removes duplicate entries, and verifies municipal urgency within 24 hours.": "नागरिक, नगरसेवक किंवा स्थानिक प्रभाग प्रमुख मजकूर, फोटो किंवा व्हॉइस नोट्सद्वारे समस्या सबमिट करतात. C2C AI इंजिन या समस्येला जिओटॅग करते, डुप्लिकेट नोंदी हटवते आणि 24 तासांच्या आत पालिकेची तातडी पडताळते.",
    "Yes. All CSR contributions are managed via escrow contracts compliance-mapped to Companies Act Section 135. Automated milestone reports, municipal utilization certificates, and receipt tokens are generated upon every payout.": "होय. सर्व CSR योगदान कंपनी कायदा कलम 135 चे पालन करणाऱ्या एस्क्रॉ करारांद्वारे व्यवस्थापित केले जातात. प्रत्येक पेआउटवर स्वयंचलित टप्पा अहवाल, पालिका वापर प्रमाणपत्रे आणि पावती टोकन्स तयार होतात.",
    "Institutional heads can register directly on the C2C portal using their official domain email (.edu.in or .gov.in). Account clearance takes less than 2 hours following automated credential verification.": "संस्थात्मक प्रमुख त्यांच्या अधिकृत ईमेल (.edu.in किंवा .gov.in) द्वारे थेट C2C पोर्टलवर नोंदणी करू शकतात. स्वयंचलित क्रेडेन्शियल पडताळणीनंतर खाते मंजुरीस 2 तासांपेक्षा कमी वेळ लागतो.",
    "Direct access to AI-matched community challenges that align with university curriculum credits. Form interdisciplinary teams, unlock hardware stipends, and submit verified engineering solutions.": "विद्यापीठाच्या अभ्यासक्रम क्रेडिट्सशी सुसंगत असलेल्या AI-मॅच केलेल्या सामाजिक आव्हानांमध्ये थेट प्रवेश. आंतरविद्याशाखीय टीम तयार करा, हार्डवेअर विद्यावेतन अनलॉक करा आणि सत्यापित अभियांत्रिकी उपाय सबमिट करा.",
    "Sovereign digital bridge unifying Smart India Hackathon innovators, public administration, university research, and civic ground telemetry for verified societal impact.": "स्मार्ट इंडिया हॅकाथॉन शोधक, सार्वजनिक प्रशासन, विद्यापीठ संशोधन आणि नागरिक टेलिमेट्री यांना एकत्रित करणारा डिजिटल सेतू.",
    "Transforms vernacular or voice distress reports into structured engineering specs, automatically routing them to department labs based on faculty domain expertise.": "स्थानिक भाषा किंवा व्हॉइस अहवालांचे संरचित अभियांत्रिकी वैशिष्ट्यांमध्ये रूपांतर करते, जे प्राध्यापकांच्या तज्ज्ञतेनुसार विभाग प्रयोगशाळांकडे स्वयंचलितपणे पाठवले जाते.",
    "Empowering ward counselors, village sarpanches, and citizens to register distress vectors with automated GPS tagging and NLP deduplication.": "नगरसेवक, सरपंच आणि नागरिकांना स्वयंचलित GPS टॅगिंग आणि NLP द्वारे समस्या नोंदवण्यासाठी सक्षम करणे.",
    "Direct CSR funding, tech hardware grants, and executive engineering mentorship under formalized Section 135 compliance.": "औपचारिक कलम 135 पालनांतर्गत थेट CSR निधी, तंत्रज्ञान हार्डवेअर अनुदान आणि कार्यकारी अभियांत्रिकी मार्गदर्शन.",
    "Real-time telemetry measuring social return on investment, state-by-state resolution velocities, and UN SDG alignment.": "सामाजिक परतावा, राज्यनिहाय निराकरण वेग आणि UN SDG सुसंगतता मोजणारी रिअल-टाइम टेलिमेट्री.",
    "From ground-level citizen distress calls to verified societal deployment, every milestone is auditable and automated.": "नागरिकांच्या तक्रारींपासून ते सत्यापित सामाजिक अंमलबजावणीपर्यंत, प्रत्येक टप्पा तपासण्यायोग्य आणि स्वयंचलित आहे.",
    "Engineered for high-volume civic scale, regulatory Section 135 compliance, and frictionless cross-sector execution.": "मोठ्या प्रमाणावरील नागरिक समस्या, कलम 135 चे नियम पालन आणि सुरळीत अंमलबजावणीसाठी डिझाइन केलेले.",
    "Discover and report ground-level issues with spatial GIS mapping, population density indexing, and urgency scoring.": "जीआयएस मॅपिंग, लोकसंख्या घनता निर्देशांक आणि तातडीच्या स्कोअरिंगसह समस्या शोधा आणि नोंदवा.",
    "Geo-tagged submissions via web portal, vernacular voice notes, or WhatsApp bots by panchayats and local residents.": "ग्रामपंचायती आणि स्थानिक रहिवाशांद्वारे वेब पोर्टल, व्हॉइस नोट्स किंवा व्हॉट्सअ‍ॅप बॉट्सद्वारे जिओ-टॅग केलेल्या नोंदी.",
    "Automated ESG reporting and Social Return on Investment (SROI) metrics formatted directly for ministerial review.": "मंत्रालयीन पुनरावलोकनासाठी थेट तयार केलेले स्वयंचलित ESG अहवाल आणि सामाजिक परतावा (SROI) मेट्रिक्स.",
    "Neural vector scoring linking citizen distress vectors to collegiate engineering proficiencies and lab inventory.": "नागरिकांच्या समस्यांना कॉलेजच्या अभियांत्रिकी कौशल्य आणि प्रयोगशाळांशी जोडणारे न्यूरल व्हेक्टर स्कोअरिंग.",
    "Pitch multidisciplinary solutions, earn verified AICTE academic credit points, and register provisional patents.": "बहुविद्याशाखीय उपाय सादर करा, सत्यापित AICTE शैक्षणिक क्रेडिट पॉइंट्स मिळवा आणि तात्पुरते पेटंट नोंदवा.",
    "Milestone-governed execution with verifiable digital proofs of work, GitHub linkage, and geofenced field audits.": "कामाचे डिजिटल पुरावे, गिटहब लिंकेज आणि जिओफेंस केलेल्या फील्ड ऑडिटसह टप्पानिहाय अंमलबजावणी.",
    "NLP models perform cross-regional deduplication, priority grading, and cross-reference with municipal datasets.": "NLP मॉडेल प्रादेशिक डुप्लिकेट काढणे, प्राधान्य क्रमवारी आणि पालिका डेटासेटशी पडताळणी करतात.",
    "Connect department research labs with municipal challenges. Turn final-year capstone theses into field pilots.": "विभाग संशोधन लॅब्सना पालिकेच्या आव्हानांशी जोडा. अंतिम वर्षाच्या प्रोजेक्ट्सचे प्रत्यक्ष पायलट प्रोजेक्ट्समध्ये रूपांतर करा.",
    "Direct portal for District Collectors and Municipal Commissioners to validate pilot proposals within 48 hours.": "जिल्हाधिकारी आणि पालिका आयुक्तांना 48 तासांच्या आत पायलट प्रस्तावांना मान्यता देण्यासाठी थेट पोर्टल.",
    "Algorithms pair the verified challenge with student engineering cohorts, department labs, and faculty guides.": "अल्गोरिदम सत्यापित आव्हानाची विद्यार्थी अभियांत्रिकी गट, विभाग लॅब्स आणि प्राध्यापक मार्गदर्शकांशी जोडणी करतात.",
    "Interdisciplinary squads assemble (e.g., 3 engineers + 1 data scientist) under an accredited faculty mentor.": "प्राध्यापक मार्गदर्शकाखाली आंतरविद्याशाखीय पथके (उदा. 3 अभियंते + 1 डेटा सायंटिस्ट) एकत्र येतात.",
    "Immutable impact quantified: liters purified, kWh saved, citizen hours recovered, and Social ROI calculated.": "कायमस्वरूपी प्रभाव: शुद्ध केलेले लिटर, वाचवलेली kWh, वाचवलेले नागरिक तास आणि मोजलेला सामाजिक ROI.",
    "Prototypes live in community. Real-time IoT feedback and citizen satisfaction ratings stream to dashboards.": "प्रोटोटाइप समाजात कार्यरत आहेत. रिअल-टाइम IoT अभिप्राय आणि नागरिक समाधान रेटिंग डॅशबोर्डवर दिसतात.",
    "University lab facilities and professors certify hardware safety, sensor calibration, and code stability.": "विद्यापीठ प्रयोगशाळा सुविधा आणि प्राध्यापक हार्डवेअर सुरक्षितता, सेन्सर कॅलिब्रेशन आणि कोड स्थिरतेचे प्रमाणन करतात.",
    "Upon dispatch, 4 shortlisted universities within a 50km radius and 2 CSR partners receive automated RFPs.": "पाठवल्यावर, 50 किमी परिसरातील 4 निवडलेली विद्यापीठे आणि 2 CSR भागीदारांना स्वयंचलित RFP प्राप्त होतात.",
    "Autonomous edge-AI drone scans for pink bollworm detection across smallholder cotton belts in Vidarbha.": "विदर्भातील कापूस पट्ट्यात गुलाबी बोंडअळी शोधण्यासाठी स्वयंचलित एज-AI ड्रोन स्कॅन.",
    "\"Hi! I'm C2C AI. Let's turn a civic challenge into an actionable solution. How can I guide you today?\"": "\"नमस्कार! मी C2C AI आहे. चला नागरी आव्हानाचे कृतीयोग्य समाधानात रूपांतर करूया. आज मी तुम्हाला कसा मार्गदर्शक ठरू शकतो?\"",
    "Corporate CSR capital, cloud compute credits, and hardware toolkits route directly to project escrow.": "कॉर्पोरेट CSR भांडवल, क्लाउड कॉम्प्युट क्रेडिट्स आणि हार्डवेअर टूलकिट्स थेट प्रकल्प एस्क्रॉकडे जातात.",
    "Continuous cellular temperature telemetry for primary healthcare storage in Gadchiroli tribal belts.": "गडचिरोली आदिवासी भागातील प्राथमिक आरोग्य सेवा साठवणुकीसाठी निरंतर तापमान टेलिमेट्री.",
    "District Collectors authorize testing grounds and road-cutting NOCs with zero bureaucratic delay.": "जिल्हाधिकारी कोणतीही प्रशासकीय दिरंगाई न करता चाचणी जागा आणि रस्ता खोदण्याची NOC मंजूर करतात.",
    "Partner: Bhiwandi Municipal Council • Host: Veermata Jijabai Technological Institute (VJTI)": "भागीदार: भिवंडी नगर परिषद • होस्ट: वीरमाता जिजाबाई तंत्रज्ञान संस्था (VJTI)",

    # Titles & Headlines
    "Sovereign Civic Orchestrator": "संप्रभु नागरी आर्केस्ट्रेटर",
    "Bridging Campus Innovation & Community Distress": "कैंपस नावीन्यता आणि नागरी समस्यांची जोडणी",
    "Real-World Problem to Verified Solution Pipeline": "प्रत्यक्ष समस्येपासून सत्यापित उपायापर्यंतची पाइपलाइन",
    "Live Sovereign Infrastructure Telemetry": "थेट संप्रभु पायाभूत सुविधा टेलिमेट्री",
    "Grassroots Challenge Intake Pipeline": "तळागाळातील आव्हान स्वीकारणारी पाइपलाइन",
    "National Social ROI & SDG Dashboard": "राष्ट्रीय सामाजिक ROI आणि SDG डॅशबोर्ड",
    "Architected for Every Sovereign Stakeholder": "प्रत्येक संप्रभु भागधारकासाठी डिझाइन केलेले",
    "4-Phase Sovereign Governance Lifecycle": "4-टप्प्यांचे संप्रभु शासन जीवनचक्र",
    "Frequently Asked Questions": "वारंवार विचारले जाणारे प्रश्न",
    "Ready to Transform Your Campus Innovation?": "तुमच्या कॉलेजमधील इनोव्हेशनला सामाजिक उपायात बदलण्यास तयार आहात?",
    "About Campus2Community": "Campus2Community बद्दल",
    "Core Vision & Mission": "मुख्य ध्येय आणि उद्दिष्टे",
    "Our Vision": "आमचे ध्येय",
    "Our Mission": "आमचे उद्दिष्ट",
    "Core Platform Pillars": "मुख्य प्लॅटफॉर्म स्तंभ",
    "Evolution & Milestones": "विकास आणि टप्पे",
    "Unified Platform Core Team": "एकीकृत प्लॅटफॉर्म कोर टीम",

    # Section Subtitles & Badges
    "GOVERNMENT APPROVED CIVIC INFRASTRUCTURE": "शासकीय मान्यताप्राप्त नागरी पायाभूत सुविधा",
    "SIH 2026 FIELD INTAKE PIPELINE": "SIH 2026 फील्ड इनटेक पाइपलाइन",
    "LIVE TELEMETRY & DISPATCH MATRIX": "थेट टेलिमेट्री आणि डिस्पॅच मॅट्रिक्स",
    "QUANTIFIABLE SOCIETAL ROI": "संख्यात्मक सामाजिक ROI",
    "UNIFIED STAKEHOLDER VALUE": "एकीकृत भागधारक मूल्य",
    "GROUND-TO-GOVERNMENT LIFECYCLE": "जमीन ते शासन जीवनचक्र",
    "EVERYTHING YOU NEED TO KNOW": "तुम्हाला माहिती असणे आवश्यक सर्व काही",
    "JOIN THE SOVEREIGN MESH": "संप्रभु जाळ्यात सामील व्हा",
    "CAMPUS2COMMUNITY ECOSYSTEM": "कैंपस2कम्युनिटी परिसंस्था",
    "VIDYALANKAR INSTITUTE OF TECHNOLOGY (VSIT)": "विद्यालंकार तंत्रज्ञान संस्था (VSIT)",

    # Card & Node Titles
    "Students & Innovators": "विद्यार्थी आणि नवसंशोधक",
    "Universities & Labs": "विद्यापीठे आणि लॅब्स",
    "Faculty Mentorship": "प्राध्यापक मार्गदर्शन",
    "Field NGO Coalition": "क्षेत्रीय एनजीओ आघाडी",
    "Social Auditing": "सामाजिक परीक्षण",
    "Industry CSR Escrow": "उद्योग CSR एस्क्रॉ",
    "Sec 135 Compliance": "कलम 135 पालन",
    "Government NOC": "शासकीय NOC",
    "District Administration": "जिल्हा प्रशासन",
    "Urban Local Bodies": "नागरी स्थानिक संस्था",

    # Metric & Stats Labels
    "Active Solvers": "सक्रिय निवारक",
    "Campuses": "कैंपस",
    "Verifiers": "पडताळणीकर्ते",
    "Committed": "कटिबद्ध",
    "CITIZENS BENEFITED": "लाभान्वित नागरिक",
    "COMMUNITIES IMPACTED": "प्रभावित समुदाय",
    "PROBLEMS SOLVED": "सोडवलेल्या समस्या",
    "ACTIVE CAPSTONE PROJECTS": "सक्रिय प्रकल्प",
    "WATER & SANITATION (SDG 6)": "पाणी व स्वच्छता (SDG 6)",
    "AGRITECH & SOIL HEALTH (SDG 2)": "कृषी तंत्रज्ञान व मृदा (SDG 2)",
    "SMART INFRASTRUCTURE (SDG 11)": "स्मार्ट पायाभूत सुविधा (SDG 11)",
    "RURAL HEALTHCARE (SDG 3)": "ग्रामीण आरोग्य (SDG 3)",

    # Filter Options & Form Fields
    "All Categories": "सर्व प्रकार",
    "Water Systems": "जल प्रणाली",
    "Urban Roads": "शहरी रस्ते",
    "Solar Microgrids": "सौर मायक्रोग्रिड्स",
    "Rural Health": "ग्रामीण आरोग्य",
    "Civic Infrastructure": "नागरी पायाभूत सुविधा",
    "Agriculture Tech": "कृषी तंत्रज्ञान",
    "Filter by Keyword or District...": "शब्द किंवा जिल्ह्यानुसार शोधा...",
    "Search Problems...": "समस्या शोधा...",
    "Search tickets, districts, SDGs...": "तिकीट, जिल्हे, SDGs शोधा...",
    "Select Priority": "प्राधान्य निवडा",
    "Critical (ULB 24h SLA)": "अत्यंत तातडीचे (ULB 24तास SLA)",
    "High Urgency": "उच्च तातडी",
    "Medium Urgency": "मध्यम तातडी",
    "Low Urgency": "कमी तातडी",

    # Buttons & Actions
    "Explore Problem Mesh": "समस्या जाळे पाहा",
    "Submit Field Distress Report": "समस्या अहवाल सबमिट करा",
    "Submit Ticket to Sovereign Mesh": "जाळ्यात तिकीट सबमिट करा",
    "Trigger Auto-NOC Dispatch": "ऑटो-NOC पाठवा",
    "View Gazetted Consent Certificate": "राजपत्रित संमती प्रमाणपत्र पाहा",
    "Join 32,000+ Student Engineers": "32,000+ विद्यार्थी अभियंत्यांमध्ये सामील व्हा",
    "Explore SIH 2026 Portal": "SIH 2026 पोर्टल पाहा",
    "Register Institution / Student Team": "संस्था / विद्यार्थी संघ नोंदणी करा",

    # Navigation & Footers
    "Overview": "आढावा",
    "Intake Pipeline": "इनटेक पाइपलाइन",
    "AI Orchestrator": "AI आर्केस्ट्रेटर",
    "Impact Telemetry": "प्रभाव टेलिमेट्री",
    "Stakeholders": "भागधारक",
    "Governance & SIH": "प्रशासन आणि SIH",
    "About Us & Platform Vision": "आमच्याबद्दल व व्हिजन",
    "Code Base & Tech Specs": "कोड बेस आणि तंत्रज्ञान",
    "Ministry of Education": "शिक्षण मंत्रालय",
    "AICTE Portal Integration": "AICTE पोर्टल एकत्रीकरण",
    "SIH 2026 Grand Finale": "SIH 2026 ग्रँड फिनाले",

    # Single Words & Common Terms
    "Students": "विद्यार्थी",
    "Innovators": "नवसंशोधक",
    "Universities": "विद्यापीठे",
    "Labs": "प्रयोगशाळा",
    "Faculty": "प्राध्यापक",
    "Mentorship": "मार्गदर्शन",
    "Field": "क्षेत्र",
    "NGO": "एनजीओ",
    "Coalition": "आघाडी",
    "Verifiers": "पडताळणीकर्ते",
    "Social": "सामाजिक",
    "Auditing": "परीक्षण",
    "Industry": "उद्योग",
    "Escrow": "एस्क्रॉ",
    "Committed": "कटिबद्ध",
    "Compliance": "पालन",
    "Government": "शासन",
    "District": "जिल्हा",
    "Administration": "प्रशासन",
    "Urban": "शहरी",
    "Local": "स्थानिक",
    "Bodies": "संस्था",
    "Active": "सक्रिय",
    "Solvers": "निवारक",
    "Campuses": "कैंपस",
    "Ticket": "तिकीट",
    "Problem": "समस्या",
    "Solution": "उपाय",
    "Status": "स्थिती",
    "Verified": "सत्यापित",
    "Pending": "प्रलंबित",
    "Resolved": "सोडवले",
    "Details": "तपशील",
    "Filter": "शोधा",
    "Search": "शोधा",
    "Submit": "सबमिट करा",
    "Close": "बंद करा",
    "Back": "मागे",
    "Next": "पुढील",
    "Previous": "मागील",
    "All": "सर्व",
    "Critical": "अत्यंत तातडीचे",
    "High": "उच्च",
    "Medium": "मध्यम",
    "Low": "कमी"
}

print("Dictionary sizes -> HI:", len(translations_hi), "MR:", len(translations_mr))

with open('scratch/dict_hi.json', 'w', encoding='utf-8') as f:
    json.dump(translations_hi, f, ensure_ascii=False, indent=2)

with open('scratch/dict_mr.json', 'w', encoding='utf-8') as f:
    json.dump(translations_mr, f, ensure_ascii=False, indent=2)
